# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'ArtworkExhibition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArtworkExhibition

  target 'ArtworkExhibitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtworkExhibitionUITests' do
    # Pods for testing
  end

  # add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
    
    pod 'Firebase/Core'
    pod 'FirebaseUI'
    pod 'Firebase/Auth'
end
